### ISSUE TITLE
In game product item buying seems to not be working. 

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#1]
In the battle.io 1.19 regular demo, not the playfab demo, when you go to buy the character package that comes with weapon, character and head, it takes the Gold but doesn't unlock anything in from the product. Also after buying it, the button to buy lets you buy it again when it should be buy only once however it still doesn't unlock anything. It might be bugged Suriyun.

**Comment by insthync** [comment]
Fixed, I will upload it today

**Comment by Vauxvogh** [comment]
Thanks Suriyun, forgot to say the bots are bugged too. If you change the default bot count in game rules it doubles it in a match. So if I set it to 9 it makes 18 bots. But if you leave it at 7 without touching it, it works fine. And If you change the max player customize on Photon Create Game script to an odd number it changes back to an even.

**Comment by insthync** [comment]
Fixed, thank you for bugs report :)

**Comment by Vauxvogh** [comment]
No problem thank you.  :) will this update include the main game level system?

**Comment by insthync** [comment]
No

**Comment by Vauxvogh** [comment]
Ok no worries Suriyun! Hey I saw in the playfab you said you made it to where it saves scores to playfab. How would I set up a leaderboard for that on playfab?

**Comment by insthync** [comment]
For now, I didn't do anything that required leaderboard yet, but I may use it for player level achievement

**Comment by Vauxvogh** [comment]
Ok sounds great Suriyun thanks.

**Comment by Vauxvogh** [comment]
Hey on playfab integration I noticed you said cant use requisite price option for in game items. Can it still be used for in game currencies? Basically can you still use requisite price option to buy currencies instead of items? So that I can still charge multiple currencies for one currency?

**Comment by insthync** [comment]
Playfab's default purchasing function does not support the requisite price option, but I can extend functionality with cloud codes.

**Comment by Vauxvogh** [comment]
Oh ok I'm sorry I dont want to make it difficult.  I just had in my game a makeshift crafting function. Where I used like a sword would cost multiple currencies like gold, iron and leather as currencies. That's why you added requisite back in the day with me Haha.  Unless we could work around this somehow my game kind of functions on it right now.  Whatever we can do I'm fine

**Comment by insthync** [comment]
Updated, you have to update this  https://github.com/insthync/dot-io-playfab-client and also setup cloudcodes  https://github.com/insthync/dot-io-playfab-cloudcodes  .
