### ISSUE TITLE
Team Death Match Not Working

### ISSUE THREAD

**Issue by jonmalave** [suriyun-production/battle-io-docs#10]
I just purchased this asset and tried testing the Team Death Match mode and it just automatically ends as soon as I join the game. There are some Photon Related Errors that can been seen in the Editor Screenshot below. I'm not sure which are important, but the Photon Team Script you are using in this asset seems to be deprecated. Could be part of the main issue. It would be good clear up the other Error you see in this screenshot as well. Hopefully you can help with this. 

![errors](https://user-images.githubusercontent.com/3487527/79084272-d548a000-7d00-11ea-8b24-174a61b292e2.jpg)

**Comment by insthync** [comment]
Yes, seems like they changes a lot, I'm going to fix it.

**Comment by insthync** [comment]
Update by import these packages:

- [PhotonBattleIO_UpdatePUN2.zip](https://github.com/suriyun-production/battle-io-docs/files/4474434/PhotonBattleIO_UpdatePUN2.zip)

- [PhotonBattleIO_UpdatePUN2-2.zip](https://github.com/suriyun-production/battle-io-docs/files/4474462/PhotonBattleIO_UpdatePUN2-2.zip)

**Comment by alextitonis** [comment]
After importing these 2 i got some errors, the first is when i just sent 1 to the values (from last foto) in order to run it
![Screenshot_151](https://user-images.githubusercontent.com/45359358/79229425-adc21680-7e6b-11ea-8bd7-f69f2e9410fc.png)

![Screenshot_149](https://user-images.githubusercontent.com/45359358/79229422-ad298000-7e6b-11ea-95ea-5921972d60a2.png)

**Comment by insthync** [comment]
Oh, I've changes something before the last fix, I have to send full package. Please send your invoice ID to email: contact@suriyun.com, then I will validate and send full package to you asap.

**Comment by alextitonis** [comment]
Please speak with Jon, im just helping him with his project

**Comment by Vauxvogh** [comment]
Hey Suriyun sorry, would you mind showing which scripts were changed in this new update 1.23 as we have alot of scripts edited and dont want to redownload everything. Thanks

**Comment by insthync** [comment]
Most changes are in `simple-photon2-networkmanager` project which is in `PhotonBattleIO_UpdatePUN2.zip` files, for other changes

![Screenshot_99](https://user-images.githubusercontent.com/2697550/79415907-a9ffd280-7fd8-11ea-95c7-ba5fab49ce19.png)

![Screenshot_100](https://user-images.githubusercontent.com/2697550/79415995-d1ef3600-7fd8-11ea-846d-56cedcc4d71c.png)

![Screenshot_101](https://user-images.githubusercontent.com/2697550/79415998-d61b5380-7fd8-11ea-8a5e-df8a7ed87469.png)

![Screenshot_102](https://user-images.githubusercontent.com/2697550/79416003-dae00780-7fd8-11ea-937b-52259a2efe50.png)

**Comment by Vauxvogh** [comment]
Thank you so much. :)

**Comment by jonmalave** [comment]
Thanks @insthync this issue was resolved with last updates
