### ISSUE TITLE
Sometimes this Bug when switching weapons from an attribute in match

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#13]
Sometimes this happens when you switch weapons if you click a weapon attribute in match. So if you're in the middle of an attack and click a weapon attribute and switch weapons the player attack animation can freeze up and it wont let you attack until you die and go back to your original weapon. It throws this error

https://i.gyazo.com/39621a7f554aa96d4e9f7e839f833cfe.png

**Comment by Vauxvogh** [comment]
Are you able to fix this one Suriyun? It happens sometimes if you switch weapons from an attribute pop up. If you are already attacking and press the weapon attribute to give you a new weapon it can freeze in that attack animation.

**Comment by insthync** [comment]
Hello, Is this still occurring ?

**Comment by Vauxvogh** [comment]
Hey suriyun yeah this is still happening. If you're in the middle of an attack animation and click a weapon switch attribute, it gets stuck in that animation and you cant attack with the new weapon until you die and reset your weapon

**Comment by insthync** [comment]
Try change function codes in DamageEntity.cs
**From Line 210**
```
    public static DamageEntity InstantiateNewEntityByWeapon(
        int weaponId,
        byte actionId,
        Vector3 direction,
        int attackerViewId,
        float addRotationX,
        float addRotationY)
    {
        WeaponData weaponData = null;
        if (GameInstance.Weapons.TryGetValue(weaponId, out weaponData))
        {
            var damagePrefab = weaponData.damagePrefab;
            var isAnimationForLeftHandWeapon = false;
            AttackAnimation attackAnimation;
            if (weaponData.AttackAnimations.TryGetValue(actionId, out attackAnimation))
            {
                if (attackAnimation.damagePrefab != null)
                    damagePrefab = attackAnimation.damagePrefab;
                isAnimationForLeftHandWeapon = attackAnimation.isAnimationForLeftHandWeapon;
            }
            if (damagePrefab)
                return InstantiateNewEntity(damagePrefab, isAnimationForLeftHandWeapon, direction, attackerViewId, addRotationX, addRotationY);
            else
                Debug.LogWarning("Can't find weapon damage entity prefab: " + weaponId);
        }
        else
        {
            Debug.LogWarning("Can't find weapon data: " + weaponId);
        }
        return null;
    }
```

**Comment by Vauxvogh** [comment]
alrighty i will try it. thank you!

**Comment by Vauxvogh** [comment]
Hey yeah that fixed it man! thank you!
