### ISSUE TITLE
Only 2 Melee Attack Animations Work

### ISSUE THREAD

**Issue by jonmalave** [suriyun-production/battle-io-docs#14]
I followed the documentation on how to setup different types of animations using the action ids. I setup 1 melee weapon to have 3 animations, set the animation speeds correctly and action ids. 

I have 3 melee attack animations in my animator, and assigned the action ids to each one from (0, 1, 2), but when I try to test in-game. Only 2 of the melee animations playback in sequence instead of 3 why is that?

**Comment by jonmalave** [comment]
@insthync any thoughts on this?

**Comment by insthync** [comment]
I will check it.

**Comment by insthync** [comment]
As I try, it is random correctly, how about action id condition in animator transition to attack clips? did you set them correctly?

**Comment by jonmalave** [comment]
> As I try, it is random correctly, how about action id condition in animator transition to attack clips? did you set them correctly?

hey don't worry... sorry i forgot to close this I found a way to make it work. Thank you!
