### ISSUE TITLE
Skill Assignment Not Working

### ISSUE THREAD

**Issue by jonmalave** [suriyun-production/battle-io-docs#16]
Hi, @insthync there is no documentation in how to setup the Skills... can you please assist with this? 

I try to setup multiple skills but only 1 skill will ever work. I tried using the Game Instance Object Settings where the Skills Inputs are listed. I create 2 or 3 Skills Inputs, Assign the Key for them, then I also Add 2-3 Skills to the Character or Weapon and only 1 out of the 3 Skills every execute. Why is this...? Please help...

**Comment by insthync** [comment]
I will write the document about it.
