### ISSUE TITLE
ClearTeams and Some objects were not cleaned up when closing the scene

### ISSUE THREAD

**Issue by TemhemKaya** [suriyun-production/battle-io-docs#17]
Exit button click error. Please help me 

https://prnt.sc/sn24yk
https://prnt.sc/sn2586

**Comment by TemhemKaya** [comment]
@insthync

**Comment by insthync** [comment]
This error won't affect gameplay, and the codes that cause error is Photon's codes, you actually can avoid it and error messages by just add null check at top of ClearTeams function

**PhotonTeamsManager.cs**

```
        private void ClearTeams()
        {
            if (playersPerTeam == null)
                return;
            foreach (var key in playersPerTeam.Keys)
            {
                playersPerTeam[key].Clear();
            }
        }

```

**Comment by TemhemKaya** [comment]
@insthync Thank you :) 1 more error : black fade not fade out when start game sometime...
error uncorrected 1.24

**Comment by insthync** [comment]
Don't fade means that it's black?

**Comment by TemhemKaya** [comment]
loading screen does not appear. Create game button and http://prntscr.com/snlr1x then game screen

**Comment by insthync** [comment]
I did not make the loading screen

**Comment by Vauxvogh** [comment]
Hey you could simply call in the button events on the "create game button" to set active the loading object under "UINetworkClientErrorAndLoadingCanvas" and it will show a loading screen while the match loads, it will disappear when you get into the match. This is not an actual loading screen though but it looks good lol

**Comment by Vauxvogh** [comment]
it would be nice to have one though like the mmo kit does that actually shows the loading bar filling. If you're interested in adding one Suriyun. However its also not that hard to script in yourself

**Comment by TemhemKaya** [comment]
I am sorry for my English :/ I wanted to tell by video: https://streamable.com/eqewwq

**Comment by TemhemKaya** [comment]
> 
> 
> Hey you could simply call in the button events on the "create game button" to set active the loading object under "UINetworkClientErrorAndLoadingCanvas" and it will show a loading screen while the match loads, it will disappear when you get into the match. This is not an actual loading screen though but it looks good lol

thank you
