### ISSUE TITLE
Add Damage Spread dont work

### ISSUE THREAD

**Issue by TemhemKaya** [suriyun-production/battle-io-docs#18]
Attributes damage spread dont damage :(  : https://streamable.com/b9a0co

**Comment by TemhemKaya** [comment]
@insthync

**Comment by insthync** [comment]
How it not work, I saw there are 2 damage entities spawned

**Comment by TemhemKaya** [comment]
> 
> 
> How it not work, I saw there are 2 damage entities spawned

Yes 2 damages entities spawned but dont damage https://streamable.com/91f3ee

**Comment by Vauxvogh** [comment]
whats his armor? did you change the bots armor? did you check all the stats?

**Comment by TemhemKaya** [comment]
> 
> 
> whats his armor? did you change the bots armor? did you check all the stats?

@Vauxvogh I dont change bots armor. Import asset store and play. BotEntity setting: http://prntscr.com/soojrl please help @insthync

**Comment by Vauxvogh** [comment]
Actually yeah Suriyun, I tested my self. Once you increase damage spread, it seems to take away the damage from the attack causing no damage.

**Comment by TemhemKaya** [comment]
> 
> 
> Actually yeah Suriyun, I tested my self. Once you increase damage spread, it seems to take away the damage from the attack causing no damage.

Yess I checked DamageEntity.cs and CharacterEntity.cs but I couldn't find the problem.

**Comment by TemhemKaya** [comment]
@insthync pls fix error

**Comment by insthync** [comment]
It's dividing damage by amount of spread so damage will be reduced

for now if you don't want it be divided, you can remove codes in `WeaponData.cs` Line 29 (`damage /= spread;`)

**Comment by TemhemKaya** [comment]
> 
> 
> It's dividing damage by amount of spread so damage will be reduced
> 
> for now if you don't want it be divided, you can remove codes in `WeaponData.cs` Line 29 (`damage /= spread;`)

thank you very much :) @insthync
