### ISSUE TITLE
Bot count bugged

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#2]
Hey Suriyun, it seems the bot count is still bugged. All do is hit play, create game, create match and the match starts it makes a random number of bots, like 15 - 20 - 32 bots sometimes its random.  I don't touch the bot count at all. Its at 7 by default but I don't touch it.

**Comment by insthync** [comment]
It is occurring for every game mode or just specific game mode?

**Comment by Vauxvogh** [comment]
Hey brother, so far I've only tried i.o mode. Will test the others today. But its the default settings for the gameplay.  I just press play in editor and click create game and go straight into a match without touching anything.  It seems to mostly work when I first start the game in the editor and start my first match, but when I leave that match and start another match them the bots are multiplied. Along with every other match after that.

**Comment by Vauxvogh** [comment]
Hey man yeah so I tested today. No I figured it out. Everything is all good it's working as it should. Here's what happened. 
I put only one head data in the game instance and a few default bots you had were set in the game instance to 1, 2 and -1 on the head data. So that I guess threw it off when it was looking for more head data but only 1 was in the game instance. So it caused them to multiply. Haha sorry that's my fault.

**Comment by Vauxvogh** [comment]
Thanks for your help.

**Comment by insthync** [comment]
[PhotonBattleIO-FixInvalidAddedBotsState.zip](https://github.com/suriyun-production/battle-io-docs/files/4005876/PhotonBattleIO-FixInvalidAddedBotsState.zip)
Fix by this package

**Comment by Vauxvogh** [comment]
Hey thanks alot Suriyun I will update this.

**Comment by Vauxvogh** [comment]
Hey how could I reduce the score of the player by 1/2 or 1/3 when they die instead of the player losing the whole score when they die?

**Comment by Vauxvogh** [comment]
Hey no the bot count is bugged again with this new update, it sets the bots at exactly double what you put into the game rule bot default count. So if I set it to 5 bots, at the start of the match it doubles it to 10. Everytime it doubles it. Not a random number but double.

**Comment by Vauxvogh** [comment]
The scoring seems bugged too in I.O mode. It doesnt scale with leveling up. I only get 10 score everytime i kill a player sometimes 11, but only those 2 numbers

**Comment by Vauxvogh** [comment]
Update: I fixed the bot doubling bug by going back to Battle.IO 1.19 Basenetworkgamerule.cs.

Scoring seems to work better right too I guess, the higher the level of the enemy player you are attacking the higher score you get from killing him. Is this right?

**Comment by insthync** [comment]
> Update: I fixed the bot doubling bug by going back to Battle.IO 1.19 Basenetworkgamerule.cs.
> 
> Scoring seems to work better right too I guess, the higher the level of the enemy player you are attacking the higher score you get from killing him. Is this right?

Yes, score higher when enemy level is higher. About bot count bug, try the package (
[BattleIO-FixAddBotsBugs.zip](https://github.com/suriyun-production/battle-io-docs/files/4038580/BattleIO-FixAddBotsBugs.zip)
)

**Comment by Vauxvogh** [comment]
Ok thanks a ton man I will get on this!
