### ISSUE TITLE
Bots dont pursue anymore

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#20]
Hey bots don't pursue each other anymore or the player like they used to. I think you changed this because of the getting stuck on walls but thats not what needed to be done. They need to calculate the blocked path and then go around the wall to still pursue the player. Right now they just wonder around while locked onto the player. 
Please change it back, or can we make smarter ai. Thanks

**Comment by insthync** [comment]
If you testing in editor, you must active on Game tab, I guess that Photon disable networking sync while client not activated.

**Comment by Vauxvogh** [comment]
No I was talking about how bots use to actually pursue enemies like monsters do, like follow distance. Right now they randomly move around their enemies position. Is there a way I can have the option of bots pursuing enemies kind of like monsters?

**Comment by Vauxvogh** [comment]
I see you added draw gizmos in the latest update but also I see you removed
" protected overide void on collision stay" on the bot entity, now if they collide into something they stay for a short moment and then update there path instead of updating it immediately. Why did you remove it? haha i think it seems to work better with it after i added it back

**Comment by insthync** [comment]
I remove it because I don't want it to find new path immediately when character stay at wall anymore, it use nav mesh system so Unity's nav mesh system should find correctly path.

**Comment by Vauxvogh** [comment]
ahh I see, alright I'll switch it back I suppose. :) Hey btw I just sent you an email about damage entity, could you take a look? its just a pic of my script. thanks

**Comment by Vauxvogh** [comment]
Hey also monsters just sit there if they run into a wall or barrier, they dont look for a new path and cant seem to get around objects, if they are locked onto you. Only once you leave, and they go back to wondering do they find a new path
