### ISSUE TITLE
Bots move upwards at start and go through walls

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#25]
Hey with the latest update all bots move upwards on the map at the start of the match. Also If the rigidbody is set to kinematic they go through walls. 
Check this video and watch

https://i.gyazo.com/2d5f5651130972c464866033f86453ec.mp4

could you fix this please, I need to be able to set there rigibody kinetmatic in the begining too for 5 secs. That doesn't seem to work anymore

**Comment by Vauxvogh** [comment]
Hey I was able to fix it temporarily by adding a Bool Cantmove, only if this bool is true is when I allow the the function void move to take place. So that works for now

**Comment by insthync** [comment]
It's dashing when start a game, I will fix it.

**Comment by Vauxvogh** [comment]
I see. Thank you! Hey it really needs an automatic matchmaking feature. Where it try's to find a match but if it cant find one then automatically make a match and fill it with bots. Like you see in all the current multiplayer games. I have 2 example scripts of how to do it in Pun 2 Also the battle royale bots need to try to stay in the circle better.Check out these two scripts perhaps as an example.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ittipon Teerapruettikulchai <notifications@github.com> Date: 7/30/20  12:13 AM  (GMT-06:00) To: suriyun-production/battle-io-docs <battle-io-docs@noreply.github.com> Cc: Vauxvogh <vauxvogh@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [suriyun-production/battle-io-docs] Bots move upwards at start and go through walls (#25) 
It's dashing when start a game, I will fix it.

**Comment by Vauxvogh** [comment]
Hey!! So sorry I just saw you added matchmaking in the new update!! You rock man! Thank you so so much!!

Sent from Mail for Windows 10

**Comment by Vauxvogh** [comment]
Hey theres a slight problem with the matchmaking. It only seems to be connecting to whatever scene is set on the "Online Scene" under "Game Network Manager". No matter what you set the filters too it will only connect to that scene. Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ittipon Teerapruettikulchai <notifications@github.com> Date: 7/30/20  12:13 AM  (GMT-06:00) To: suriyun-production/battle-io-docs <battle-io-docs@noreply.github.com> Cc: Vauxvogh <vauxvogh@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [suriyun-production/battle-io-docs] Bots move upwards at start and go through walls (#25) 
It's dashing when start a game, I will fix it.
