### ISSUE TITLE
Matchmaking problem

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#26]
Hey theres a slight problem with the matchmaking. It only seems to be connecting to whatever scene is set on the "Online Scene" under "Game Network Manager". No matter what you set the filters too it will only connect to that scene.

**Comment by Vauxvogh** [comment]
I figured it out, I just had to add some code to the matchmaking script.

**Comment by insthync** [comment]
How you fix it ?

**Comment by Vauxvogh** [comment]
I added this code from ui photon game create script, and it seems to work fine. however sometimes my name doesn't show the very first time i start a match. But that only happens every now and then

this code: 
var networkGameManager = SimplePhotonNetworkManager.Singleton as BaseNetworkGameManager;

SimplePhotonNetworkManager.Singleton.SetRoomOnlineScene(filter.onlineScene);
networkGameManager.SetGameRule(filter.gameplayRule);

**Comment by Vauxvogh** [comment]
Also ads dont seem to work anymore, you might have to change some code. I'm using unity 2019.4.7. It automatically installs advertisement and thus wont let you have monetization from asset store installed with it.
