### ISSUE TITLE
Ads not working

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#27]
Ads don't seem to work anymore, you might have to change some code. I'm using unity 2019.4.7. It automatically installs advertisement and thus wont let you have monetization from asset store installed with it. 

I've tried removing the advertisement package from the package manager, reinstalling. I've tried installing the monetization package from the asset store and package manager and nothing is working.

**Comment by insthync** [comment]
Try add `UNITY_PURCHASING`, `UNITY_ADS` to scripting define symbols

![Screenshot_16](https://user-images.githubusercontent.com/2697550/90572884-4a604080-e1df-11ea-8a6a-ce477ba2c6c5.png)

**Comment by Vauxvogh** [comment]
Hey yep that worked! Thanks
