### ISSUE TITLE
A couple of new  bugs

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#3]
Hey Suriyun I found a few bugs.

#1 It seems with the new hide area when a bot walks into it, they disappear like they should but when they leave the hide area they are still invisible and you can't see them but you can see there attack damages.

#2 Also when inside the hide area the bots can still see me even though they are outside the hide area. 

- I think the hide area should be when you enter it you are invisible but if you attack while inside of it you become visible again

#3 When I try to play single player and go to create game the level doesn't start at first but rathers throws an error saying " ArgumentNullException: Value cannot be null.
Parameter name: key" But if you click create game again it then works. So you have to press the create game twice on single player to play a match.

**Comment by Vauxvogh** [comment]
The single player bug points to this line in uiphotonwaitingroom.cs when i double click on it

line 219  
if (waitingPlayers.ContainsKey(id))

**Comment by insthync** [comment]
Fix `uiphotonwaitingroom.cs` problems 
[BattleIO-FixEmptyOfflineUserId.zip](https://github.com/suriyun-production/battle-io-docs/files/4038860/BattleIO-FixEmptyOfflineUserId.zip)

**Comment by Vauxvogh** [comment]
Hmm it seems that was only part of it I think, I still get this when I click create game for the first time

https://i.gyazo.com/edbb42a6d8f80e1c2d2d6f52fb4ff88b.png

So it doesnt work the first time you click create game but it works the second time you click create game it goes into the match. But also if you are online mode, then switch to offline mode it works fine.

**Comment by insthync** [comment]
[BattleIO-FixEmptyOfflineUserId.zip](https://github.com/suriyun-production/battle-io-docs/files/4041470/BattleIO-FixEmptyOfflineUserId.zip)
Try this again.

**Comment by Vauxvogh** [comment]
hmm alright I get this now
https://i.gyazo.com/f7d85a19fb8127d56aeda5df449cc66e.png

seems theres not an offline ID reference in the simplephotonnetworkmanager.cs

**Comment by Vauxvogh** [comment]
https://i.gyazo.com/40872cb5d3e4b257f55df00eab87954f.png

**Comment by Vauxvogh** [comment]
Hwy I fixed it Suriyun, I added this line to simplephotonnetworkmanager.cs
https://i.gyazo.com/de605a5722531f40fb650647c9ae6416.png

**Comment by insthync** [comment]
Yeah, it's actually can update from this https://github.com/insthync/simple-photon2-networkmanager

**Comment by Vauxvogh** [comment]
Haha ah ok man I gotta remember to look at that stuff. Alright thanks

**Comment by Vauxvogh** [comment]
Hey here is one other bug, Could you try fixing the scoring and kills? If I set the total kills on deathmatch to 10, and play a match and get 9 kills then I land the final kill of 10 the match ends but it only shows the player has 9 kills. It didnt update it to 10. So it the ending of the match works right but it doesnt update the Last kill. It only shows 9. It does the same for Scores too. If the set score is 100 and say I have 94 score and get another kill putting the score to 104 and winning the match. But the score still only shows 94.

**Comment by insthync** [comment]
Okay, I will fix it.

**Comment by Vauxvogh** [comment]
Ok thanks
