### ISSUE TITLE
Update for battle.io

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#32]
Hey Suriyun is there an update coming soon to battle.io? There are a few pun problems that need some fixing

-sometimes when the master leaves then rejoins a room, more bots are spawned than the limit.
-damage entities can be lagged to other players other than master // not sure if this is just me, I don't think so though
-teams are not spawning the correct amount for each team. If its 6 players, sometimes one team has 4, the other 2. its uneven
-teams are not spawning in designated team spawn areas

just checking, Thanks for your work, I know you been busy on MMO :)

**Comment by insthync** [comment]
Okay, I starting to make an update today.

**Comment by Vauxvogh** [comment]
Awesome Thanks alot man! 

A few suggestions / fixes that it needs:

- cooldown popups if the player has a status effect applied to them (so they know when the effect is over)

- a countdown before the match begins. Like 5 second countdown where players can't move or attack. 

- sometimes it picks the same Bot Name twice or more when picking random Bots. Can it be where it doesn't pick the same bot name but all different ones. 

- could use set spawn points where if 1 player is already in that spawn point, then it looks for another spawn point.  To prevent players from spawning too close to each other at start of match.  Just beginning of match for this.

- traps apply status effects

**Comment by Vauxvogh** [comment]
Hey also the AI bots for battle royale could use some work to move in towards the center with the closing circles better or rather just stay away from the closing circle like try to avoid it.  If you can
