### ISSUE TITLE
Last match result bug

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#34]
Last match Result doesnt show for all players after match, only the master client player.

Also it seems sometimes when master client leaves, all bots disappear sometimes or some do, then if a new player joins the bots are added again or some of them. Still testing this. Sometimes it always works but sometimes the master client leaving takes bots away now.

**Comment by insthync** [comment]
I'm Fixing it.

**Comment by Vauxvogh** [comment]
Hey thanks a ton! I'll close these issues

**Comment by insthync** [comment]
I just uploaded a new version.

**Comment by Vauxvogh** [comment]
Hey you're the man! Thanks guys
