### ISSUE TITLE
Last match result still not working

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#35]
Hey Suriyun, the Last match result is still only showing for the master server player after a match and not all the players.

**Comment by insthync** [comment]
Last match result, is this?

![Screenshot_125](https://user-images.githubusercontent.com/2697550/101229395-a093b980-36d2-11eb-8e34-01d191af2100.png)

**Comment by Vauxvogh** [comment]
Hey sorry no it's the match reward that pops up on the main menu after a match is over depending on what place you came in, it's on death match and battle royale I believe. You know match reward handler and last match result

**Comment by Vauxvogh** [comment]
This is match reward after match. Only shows for master server player

![matchreward](https://user-images.githubusercontent.com/56084228/101236210-e16cdd80-3694-11eb-893a-70506ff34847.png)

**Comment by Vauxvogh** [comment]
Hey Battle.Io could also use a 5 second countdown timer where players or bots cant move, right when everyone joins the room before the match starts. But this should only be a single instance that plays at the start of a match, not when new players join later.

If you can throw that in there thanks man
