### ISSUE TITLE
Match Reward seems to still not be working

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#36]
Hey sorry man Match reward still does not show for the other players other than master client.
Tested with fresh install of latest version too, with no bots and only 2 players on DeathMatch.

- the deathmatch Gameplay Rule Data has 3 rewards set in the inspector for First, Second, and Third place. So thats all set so
dont know why it wouldn't work.

**Comment by Vauxvogh** [comment]
Does it work on your end? Also if you have fix could you please post it on here. thanks man

**Comment by insthync** [comment]
Did you try `1.26c`, I've tested it many time seems like it was fixed.

**Comment by Vauxvogh** [comment]
Hey yeah I tested on 1.26c with fresh install. You tested for match reward? Showing on both clients after match is over and back on main menu?

**Comment by Vauxvogh** [comment]
It's just not rewarding the other player for me. Only the master client player or whoever made the match.

**Comment by insthync** [comment]
Here is my test result
![Screenshot_136](https://user-images.githubusercontent.com/2697550/101862088-2b2d5a80-3ba4-11eb-8669-0f5a3d3d91cc.png)
![Screenshot_137](https://user-images.githubusercontent.com/2697550/101862101-2ec0e180-3ba4-11eb-9302-3e0a7785602b.png)
![Screenshot_138](https://user-images.githubusercontent.com/2697550/101862107-31233b80-3ba4-11eb-9ca6-3b21390bd2e3.png)
![Screenshot_139](https://user-images.githubusercontent.com/2697550/101862111-33859580-3ba4-11eb-9178-c1b6c14b343b.png)

Bots were included for ranking, not sure that when you test there are bots or not.

**Comment by Vauxvogh** [comment]
Yeah that's working I see! Haha man I don't know what gives on my end. I created a fresh project and fresh install and it's not working. Is my package manager not updating battle.io correctly?

Like on mine is says the version is 1.26c but under currently downloaded it says 1.26.0

Does yours say that?

**Comment by Vauxvogh** [comment]
Im also testing from an android build. Would that have something to do with it? Could you send me the main script you changed to get it work` if you dont mind?

**Comment by Vauxvogh** [comment]
I tested on Pc as well and no I'm not getting those results. Maybe you could send your unity file of battle.io 1.26c?
