### ISSUE TITLE
In online mode, opponent character's movement looks shaky like it jitters on local player's phone - Any way to set for smooth movement like position interpolation?

### ISSUE THREAD

**Issue by isaanyoha** [suriyun-production/battle-io-docs#40]
In online mode, opponent character's movement looks shaky like it jitters on local player's phone - Any way to set for smooth movement like position interpolation?
_Using Battle.io - LiteNetLibManager_

**Comment by insthync** [comment]
Find CharacterEntity or BotEntity prefabs in Project then try change `LiteNetLibTransform` settings

**Comment by isaanyoha** [comment]
Ok, I will look at that. Thanks for responding!

**Comment by isaanyoha** [comment]
Wow! It works o. Thanks! You are the best!
