### ISSUE TITLE
Also experiencing Animation lag from non master player clients

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#42]
The Master server client player can see the other players running animations just fine and smooth, they aren't lagging. 
But on other players clients the other players running animations are lagging and like restarting as they are moving. They aren't jittery as in skipping around, just the animations seemed lagged, The running/moving animation is lagging and restarting over and over. 

Any fix for this?

**Comment by isaanyoha** [comment]
Hi @Vauxvogh please what is the difference between Master server and the normal server. I watched the YouTube video Suriyun's youtube video where he setup for Master server and regular server. What is the difference between the both type of server?

**Comment by isaanyoha** [comment]
@Vauxvogh Also, please can you give me a social media link where I can reach you easily, looks like we got something in common -> battle.io

**Comment by Vauxvogh** [comment]
@isaanyoha  hey we are using different versions, im using pun 2 version. You're using the other
