### ISSUE TITLE
Game becomes unplayable when you spawn 100 bots at a time on the offline mode

### ISSUE THREAD

**Issue by isaanyoha** [suriyun-production/battle-io-docs#43]
Game becomes unplayable when you spawn 100 bots at a time on the offline mode. Can upto 100 persons play games made with the battle.io kit, including the online mode? Are there things I have to set to fix this issue?

**Comment by insthync** [comment]
Photon version or LiteNetLib?

Bots in Photon version will be controlled by master client and sync all data to other clients, so if the master-client does not have a good internet it will be disconnected easily.

**Comment by isaanyoha** [comment]
Oh ok. Thanks!
