### ISSUE TITLE
is a block feature possible?

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#46]
Hey could you maybe add a block feature to block attacks? So if a weapon is equipped with a shield, maybe have a button to be able to block. kind of like how players can dash. This was if a weapon has a shield maybe its not useless haha

**Comment by insthync** [comment]
Okay, I will add it.

**Comment by Vauxvogh** [comment]
Awesome, sounds good Suriyun. Any roadmap for the next update? Thanks

**Comment by Vauxvogh** [comment]
This is Pun 2 version by the way

**Comment by insthync** [comment]
It may be done this weekend, it seems like I wouldn't have other works.
