### ISSUE TITLE
-Mobile input

### ISSUE THREAD

**Issue by marchenterprise** [suriyun-production/battle-io-docs#48]
- Mobile and Keyboard input

I can't find any documentation or tutorials to add mobile input functionality.  Should I refer to it somewhere?

**Comment by marchenterprise** [comment]
- Mobile and Keyboard input

I can't find any documentation or tutorials to add mobile input functionality.  Should I refer to it somewhere?

**Comment by Vauxvogh** [comment]
in the Game Instance in the home scene you will see a box to check in the inspector to show the mobile input if you'd like to test it. Otherwise it automatically triggers mobile input when you are testing it on a phone.

**Comment by marchenterprise** [comment]
Thank you very much.  Please continue to create better products!
