### ISSUE TITLE
players and bots are spawning at wrong point

### ISSUE THREAD

**Issue by burakhrk** [suriyun-production/battle-io-docs#49]
players and bots are spawning at wrong point

**Comment by insthync** [comment]
How is it wrong?, It will spawning randomly in spawn area.

**Comment by burakhrk** [comment]
![2021-04-21 (4)](https://user-images.githubusercontent.com/81756834/115548999-c94ad300-a2b0-11eb-92ed-fc48b8f5e632.png)

**Comment by burakhrk** [comment]
![Uploading 2021-04-21 (5).png…]()

**Comment by burakhrk** [comment]
![2021-04-21 (5)](https://user-images.githubusercontent.com/81756834/115549778-b2f14700-a2b1-11eb-8d2b-41b43979a772.png)

**Comment by insthync** [comment]
Mine still working correctly, you should send me your invoice ID then make an appointment to check on your project (may access via TeamViewer)

**Comment by burakhrk** [comment]
> Mine still working correctly, you should send me your invoice ID then make an appointment to check on your project (may access via TeamViewer)

okey ı will send you tomorrow,  ı left the office for today
