### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by hope201314** [suriyun-production/battle-io-docs#5]
version 1.22

The bugs in this version of the case are so serious that I cannot run the game normally!

1.Battle Royale Mode Error：
    NullReferenceException: Object reference not set to an instance of an object
    DamageEntity.ApplyDamage (CharacterEntity target) (at 
    Assets/BattleIO/Scripts/GamePlay/DamageEntity.cs:183)
    DamageEntity.OnTriggerEnter (UnityEngine.Collider other) (at 
    Assets/BattleIO/Scripts/GamePlay/DamageEntity.cs:148)
2. Exit scene error：
    Some objects were not cleaned up when closing the scene. (Did you spawn new GameObjects 
    from OnDestroy?)
    The following scene GameObjects were found:
    Hitcircle
    RangeExplodeEffect(Clone)
    Hitcircle
    RangeExplodeEffect(Clone)
    Hitcircle
    RangeExplodeEffect(Clone)
    RangeExplodeEffect(Clone)
    Hitcircle

**Comment by insthync** [comment]
I will upload new version which fix it tomorrow

**Comment by hope201314** [comment]
> I will upload new version which fix it tomorrow

Version1.22

There are some additional bugs.

Error
1.Battle Royale Mode Error：
NullReferenceException: Object reference not set to an instance of an object
DamageEntity.ApplyDamage (CharacterEntity target) (at Assets/BattleIO/Scripts/GamePlay/DamageEntity.cs:183)
DamageEntity.OnTriggerEnter (UnityEngine.Collider other) (at Assets/BattleIO/Scripts/GamePlay/DamageEntity.cs:148)
2.TeamDeath Mode/Death Mode : Exit Button Error
Some objects were not cleaned up when closing the scene. (Did you spawn new GameObjects from OnDestroy?)
The following scene GameObjects were found:
Hitcircle
RangeExplodeEffect(Clone)
3.The wall blocks the character.（battle scene）
4.TeamDeath Mode:Result can not show correctly;Red team and blue team results are not displayed properly!
5.Exit Map Error:
Some objects were not cleaned up when closing the scene. (Did you spawn new GameObjects from OnDestroy?)
The following scene GameObjects were found:
RangeExplodeEffect(Clone)
Hitcircle
Hitcircle
RangeExplodeEffect(Clone)
Hitcircle
RangeExplodeEffect(Clone)
RangeExplodeEffect(Clone)
Hitcircle

Two warnings:
1.Cannot initialize purchasing, Unity Purchasing is not enabled or not supported platforms.
UnityEngine.Debug:LogWarning(Object)
MonetizationManager:InitializePurchasing() (at Assets/BattleIO/Monetization/Scripts/MonetizationManager.cs:179)
MonetizationManager:Awake() (at Assets/BattleIO/Monetization/Scripts/MonetizationManager.cs:112)
2.Cannot initialize advertisement, Unity Ads is not enabled or not supported platforms.
UnityEngine.Debug:LogWarning(Object)
MonetizationManager:InitializeAds() (at Assets/BattleIO/Monetization/Scripts/MonetizationManager.cs:126)
MonetizationManager:Awake() (at Assets/BattleIO/Monetization/Scripts/MonetizationManager.cs:111)


2020-2-17

**Comment by insthync** [comment]
I said I've uploaded it doesn't mean it will be published immediately, You have to wait for Unity asset store team to publish the update

**Comment by hope201314** [comment]
ok  Thank you

**Comment by insthync** [comment]
Unity asset store team take longer time than usual to update it, I will tell them about this, but if you want the update immediately, send your invoice id to contact@suriyun.com
