### ISSUE TITLE
fixed 

### ISSUE THREAD

**Issue by burakhrk** [suriyun-production/battle-io-docs#51]
ı  couldnt complete the getting started part . ı keep havşng errors after doing everything you said in video ı still get this errors can u check
![2021-04-21 (2)](https://user-images.githubusercontent.com/81756834/115542630-23479a80-a2a9-11eb-9c75-7bde790abf92.png)

**Comment by insthync** [comment]
Where you got the package? why there are so many missing files?

**Comment by burakhrk** [comment]
> Where you got the package? why there are so many missing files?

ı bought it . the reason was because ı hadnt updated it

**Comment by insthync** [comment]
Send me your invoice ID to my email: ittipon.bay@gmail.com
