### ISSUE TITLE
Issue with new character controller from past 2 updates

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#53]
Hey sorry Suriyun but something is wrong with new character controller and movements. Its great but knockback from explosion force messes everything up now. Players now go through the floor and the walls and have constant force applied to them even when they are dead. Its quite buggy now

**Comment by insthync** [comment]
Fixed

**Comment by Vauxvogh** [comment]
Thank you Suriyun!
