### ISSUE TITLE
Unlocking after purchasing an item

### ISSUE THREAD

**Issue by satoshi512** [suriyun-production/battle-io-docs#54]
I can buy items in the playfab demo, but they are not unlocked and my items are still "2/2". 
As for the settings, I intend to make purchaseable settings such as "install playfab demo", "add SDK", "API settings on the playfab side, catalog item price settings, cloudscript settings", but unlocking is unlocked, It will not be.  
Is this my lack of settings?  Or is it one of the bugs?  
If you don't use playfab, it seems to be unlocked after you purchase the item.

**Comment by insthync** [comment]
Did you export game data and import it in Playfab's Dashboard?

**Comment by satoshi512** [comment]
thank you for your answer.  excuse me.  Is it a catalog or currency export?  I've tried it with "PlayfabClientDemo", but I don't know what other game data is if it's as "Readme" or "guide".

**Comment by insthync** [comment]
Yes, it is catalog / currecy export

**Comment by satoshi512** [comment]
They have already been imported into playfab as described in the manual.

**Comment by insthync** [comment]
Try update this: https://github.com/insthync/dot-io-playfab-client/blob/master/Scripts/PlayfabOverridePurchaseFunctions.cs

**Comment by insthync** [comment]
[PlayfabClientDemo.zip](https://github.com/suriyun-production/battle-io-docs/files/7358685/PlayfabClientDemo.zip)

**Comment by satoshi512** [comment]
Thank you very much.  I updated to "PlayfabClientDemo" and unlocked it.  However, "Can Buy Only Once" doesn't seem to work, and I can buy "Character Pack 01" many times.

**Comment by satoshi512** [comment]
It seems that it will be possible to purchase again by destroying the bundle.  However, there seems to be no problem because the "single item" can only be purchased once.  Thank you for your response.
