### ISSUE TITLE
Attributes dont switch weapons anymore or apply status effects with new udate

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#55]
Hey attributes don't change weapons anymore if you select the option to change a weapon. It doesn't work and isn't in the code. I also had gotten it to apply status effects but they cant do that anymore either. Could you help please?

**Comment by insthync** [comment]
I will fix it.

**Comment by insthync** [comment]
Fixed

**Comment by Vauxvogh** [comment]
Thanks so much!
