### ISSUE TITLE
Can you upgrade pun2 to Fusion?

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#59]
Hey photon Fusion is out can you upgrade pun 2 to Fusion please?

**Comment by insthync** [comment]
No, I can't but I am making a new package which is a mix of Battle IO, Shooter IO, and Bomber IO because it is pretty tired to make the same update (fix same bugs, add the same features sometime) for all of them.

**Comment by Vauxvogh** [comment]
Oh that's awesome to hear, I look forward to that. I combined Battle.io and Shooter.io back in the day so this new package would be better suited for me. Any chance the new one will use photon Fusion? Have you heard about that yet?

**Comment by insthync** [comment]
It use Photon Fusion to develop :)

**Comment by Vauxvogh** [comment]
Incredible, thanks Suriyun. Not trying to rush at all, just seeing a time frame here if it's worth it for me to go ahead and try to convert mine to fusion or wait for this package?
