### ISSUE TITLE
Disconnecting - reconnecting bug

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#6]
Hey Suriyun there seems to be a crucial bug - when you are playing online and then if you get disconnected, but then try to play another match, when the match loads it seems to try to load twice, and then on the scoreboard the the player rank number says #NA and the match is all messed up.  
-This only happens if you get disconnected and then try to play another match
thanks

**Comment by insthync** [comment]
I'll check it.

**Comment by Vauxvogh** [comment]
Hey Thanks Suriyun I see you updated the package with a fix, thanks. Would you mind just posting the scripts you changed to fix it? So that I don't have to re download the whole pack because I've changed other scripts and don't want to accidentally replace a script I didn't need to replace. Thanks

**Comment by insthync** [comment]
Just update [Simple Photon 2 Manager](https://github.com/insthync/simple-photon2-networkmanager) 
- [Fix Invalid Disconnected UI State](https://github.com/insthync/simple-photon2-networkmanager/commit/1e1a912205f8e41110227321710652e1480ea596)
- [Extra(Improve error message)](https://github.com/insthync/simple-photon2-networkmanager/commit/1a0798d987008ea1cb09ef77217c857a45964e5a)

**Comment by Vauxvogh** [comment]
Thank you!

**Comment by Vauxvogh** [comment]
hey sorry suriyun I don't thinks its fixed yet. Just got disconnected from a match, then I tried to play a new match and when it loads up this what happens

**Comment by Vauxvogh** [comment]
![DataMessup](https://user-images.githubusercontent.com/56084228/77862197-7ef73f80-71df-11ea-833b-3bc8db2b8daa.png)

**Comment by Vauxvogh** [comment]
It doesn't register anything
- side note-
after getting disconnected i went to single player and tried a new match and this happens.
It doesnt seem to happen if you try playing another online match

**Comment by insthync** [comment]
Update https://github.com/insthync/simple-photon2-networkmanager again.

Commit info https://github.com/insthync/simple-photon2-networkmanager/commit/7cac32962f738cebb436298e813c154c92d08de7

**Comment by Vauxvogh** [comment]
ok thanks, hey status effect seems bugged everytime i make a new status effect entity it gives it a negative hash ID and wont let me change it, Then when trying to use the status effect entity in game it throws this error, and all players arent able to attack.

"float.NaN has been passed into WaitForSeconds which will result in an infinite wait time.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)"

**Comment by Vauxvogh** [comment]
im using unity 2019.3.6 if that helps, since it seems to use unity editor to get hash Id?
