### ISSUE TITLE
(Help)Error updating Pun2

### ISSUE THREAD

**Issue by BizachiCode** [suriyun-production/battle-io-docs#67]
![image](https://github.com/suriyun-production/battle-io-docs/assets/106054872/bf65daf0-e885-461d-97e8-0ea6d3ec8295)
I bought the kit and installed the latest version and followed the Pun2 installation steps, but it gave me an error, how can I solve this 😭?

**Comment by insthync** [comment]
Please wait , I will fix it this Sunday

**Comment by insthync** [comment]
I actaully wrote in the description page that I've made it open-source, don't you read it?

**Comment by BizachiCode** [comment]
I read this in the documentation but wanted to support the developer 😄

**Comment by insthync** [comment]
https://github.com/insthync/unity-simple-monetization/commit/514798dd104bfdb613cccd36e728e268ac802105
