### ISSUE TITLE
status effect Entity bugged

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#8]
Status effect entity not working because its only creating  negative hash ids when I create a new status effect. It doesnt let me change it, and when trying to use the -hash id Status Effect Entity on a skill in game it throws this error and everyone stops attacking

"float.NaN has been passed into WaitForSeconds which will result in an infinite wait time.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)"

im using unity 2019.3.6

**Comment by Vauxvogh** [comment]
UPDATE* I have updated unity to 2019.3.7 and it seems to be working, i created 2 status effect enities and they started as negative but then I changed the prefab name and they changed to a positive number. Just made a new one and it stayed negative but it works. So it seems like its all good.

**Comment by insthync** [comment]
It can have the negative hash id, it's not the problem. The thing that I don't know is when it pass hash id to WaitForSeconds ?

**Comment by Vauxvogh** [comment]
Yeah im not sure about that, I think that is happening if the lifetime is set to 0 on the status effect.  But it seems to be working right now.  :)
