### ISSUE TITLE
Bots getting stuck on walls

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#9]
So with the Nav mesh set up and everything the bots still get stuck on walls and objects when pursuing another player, the same for the monsters. So for instance if they notice another player behind a wall they run straight to the edge of the wall trying to get through instead of automatically finding a way around following the navmesh. Also if they are chasing someone and they run into an object they get stuck on it for a bit. 

Is there an better way to optimize this? Or am I doing something wrong?

**Comment by jonmalave** [comment]
> So with the Nav mesh set up and everything the bots still get stuck on walls and objects when pursuing another player, the same for the monsters. So for instance if they notice another player behind a wall they run straight to the edge of the wall trying to get through instead of automatically finding a way around following the navmesh. Also if they are chasing someone and they run into an object they get stuck on it for a bit.
> 
> Is there an better way to optimize this? Or am I doing something wrong?

Are you still having an issue here with this? 

@insthync have you have a chance to look into this? As I also have the same problem... Bots get stuck on trees, or other objects on my map. They are not very smart to go around objects most times.
